apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  resources:
    requests:
      storage: 500Mi
  accessModes:
    # ReadWriteOnce: Can be used by a single node
    # ReadOnlyMany: Multiple nodes can read from this
    # ReadWriteMant: Can be read and written to by many nodes
    - ReadWriteOnce
