apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
      - name: server
        image: benhany/multi-server
        ports:
        - containerPort: 5000
        env:
          - name: REDIS_HOST
            value: redis-cluster-ip-service
          - name: REDIS_PORT
            value: '6379'
          - name: PGUSER
            value: islam
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                # The name of the secret object we created
                name: pgpassword
                # The key from the key=value pair used when creating the secret object
                key: PGPASSWORD
          - name: PGHOST
            value: postgres-cluster-ip-service
          - name: PGPORT
            value: '5432'
          - name: PGDATABASE
            value: postgres