language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t benhany/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true benhany/react-test npm run test

after_success:
  - docker build -t benhany/multi-client ./client
  - docker build -t benhany/multi-nginx ./nginx
  - docker build -t benhany/multi-server ./server
  - docker build -t benhany/multi-worker ./worker
  # push images to docker hub
  # login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push benhany/multi-client
  - docker push benhany/multi-nginx
  - docker push benhany/multi-server
  - docker push benhany/multi-worker